version: '3.8'
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="37shs840dsjtlf0fhdhs85jsis8ff02jsveo9"
      - LLM_PROVIDER=openai
      - VECTOR_DB=lancedb
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      - AGENT_SERPER_DEV_KEY="SERPER DEV API KEY"
      - AGENT_SERPLY_API_KEY="Serply.io API KEY"
      - CORSHEADER=http://172.28.1.1:3000
      - PROXY=true
    volumes:
      - anythingllm_storage:/app/server/storage
    restart: always

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app/server/storage 
